/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 16 06:22:18 GMT 2019
 */

package org.apache.commons.collections4;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.FunctorException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FunctorException_ESTest extends FunctorException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FunctorException functorException0 = new FunctorException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FunctorException functorException0 = new FunctorException((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FunctorException functorException0 = new FunctorException("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("W");
      FunctorException functorException0 = new FunctorException("", mockThrowable0);
  }
}
